### ISSUE TITLE
install promgent all in one

### ISSUE THREAD

**Issue by or0or1** [line/promgen#118]
#### 1、introduce

   Promgen is a configuration file generator for Prometheus. Promgen is a web application written with Django and can help you do the following jobs.<br>
       Create and manage Prometheus configuration files
       Configure alert rules and notification options
   

   all in one：192.168.3.134.

#### 2、install redis
```
docker run --rm --net=host  --name redis -d redis
```

#### 3、install mysql
```
docker run --rm  --name mysql --net=host -e MYSQL_ROOT_PASSWORD=secret -d percona/percona-server:latest
```
create db：
```
mysqladmin -uroot -h 192.168.3.134 -p create  promgen
```

#### 4、install prometheus
```
cd /root
mkdir prometheus

cat > /root/prometheus/prometheus.yml<EOF
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    cluster_name: 'promtheus'

rule_files:
- "/etc/prometheus/promgen.rule.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'promgen'
    file_sd_configs:
      - files:
        - "/etc/prometheus/promgen.json"

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
    file_sd_configs:
      - files:
        - "/etc/prometheus/blackbox.json"
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
EOF
chmod 777 -R prometheus


docker run --name prometheus --rm -d --net=host -v $(pwd)/prometheus:/etc/prometheus:rw  prom/prometheus:latest
```

#### 5、initial
```
mkdir -p ~/.config/promgen
chmod 777 ~/.config/promgen
docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen:v0.30 bootstrap
```
input：
```
  mysql://root:secret@192.168.3.134/promgen
  redis://192.168.3.134:6379/0
```
configs need to modify:
```
cat ~/.config/promgen/promgen.yml

prometheus:
  url: http://192.168.3.134:9090/
```

#### 6、migrate & createsuperuser

```
docker run --rm -v ~/.config/promgen:/etc/promgen/ line/promgen migrate
docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen:v0.30 createsuperuser
```

#### 7、 boot promgen web
```
docker run --rm -d  --net=host -v ~/.config/promgen:/etc/promgen/ line/promgen:v0.30

```

#### 8、register msg

```
#docker exec 59e0b45181ed  /usr/local/bin/promgen register Default 192.168.3.134 9090
```
here the docker id is promgen web docker id  last step.

#### 9、boot monitor service

```
docker run --net=host -d  --rm -v ~/.config/promgen/:/etc/promgen/ -v /root/prometheus/:/etc/prometheus/:rw line/promgen:v0.30 worker --queues 192.168.3.134
```
#### 10、others
    left for future about install blackbox/altermanager and so on.
