### ISSUE TITLE
TypeError at /service/1/rule

### ISSUE THREAD

**Issue by fglaeser** [line/promgen#276]
when I try to add a new rule I get this error.
```
TypeError at /service/1/rule
expected str, bytes or os.PathLike object, not NoneType
Request Method: | POST

http://localhost:8000/service/1/rule
2.2.10
TypeError
expected str, bytes or os.PathLike object, not NoneType
/usr/local/lib/python3.6/os.py in fsencode, line 800
/usr/local/bin/python
3.6.9
['/usr/src/app',  '/usr/local/bin',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/usr/src/app']
Mié, 13 May 2020 02:22:32 +0000
```

**Comment by kfdm** [comment]
This seems like it could be similar to #274 
Can you check the value of the promtool setting in promgen.yml ?

```yaml
prometheus:
  url: http://prometheus:9090/
  # Path to promtool to verify valid rules file
  promtool: /usr/local/bin/promtool
```
