### ISSUE TITLE
[QUESTION] Prometheus Parameter

### ISSUE THREAD

**Issue by vabene1111** [line/promgen#346]
I have a multi target exporter which is controlled via the `params` config directive. 

I could not find a way to pass my parameters to the target using promgen. Do i just manually add them to the URL/metrics path ?

I am relatively new to prometheus and still trying to understand promgen as well so i hope i haven't missed anything. 

example from 
https://prometheus.io/docs/guides/multi-target-exporter/#configuring-modules

```
- job_name: blackbox-http # To get metrics about the exporter’s targets
  metrics_path: /probe
  params:
    module: [http_2xx]
    target: [prometheus.io]
  static_configs:
    - targets:
      - localhost:9115
```

thanks for the help
