### ISSUE TITLE
Static files not being served

### ISSUE THREAD

**Issue by Tommassino** [line/promgen#67]
Hi, I recently updated to v0.25 promgen from my custom branch and im running into issues with static files not being served. See the demonstration below, where the css files are not being served.

![image](https://user-images.githubusercontent.com/698950/36976825-3b9d12e0-207f-11e8-8151-4b03d75bdaab.png)

I looked if I can get anything useful out of the log, but all I can get is:
```
web_1           | [05/Mar/2018 13:08:01] "GET /login/?next=/ HTTP/1.1" 200 5341
web_1           | [05/Mar/2018 13:08:02] "GET /static/css/bootstrap.min.css HTTP/1.1" 404 4529
web_1           | [05/Mar/2018 13:08:02] "GET /static/css/bootstrap-theme.min.css HTTP/1.1" 404 4535
web_1           | [05/Mar/2018 13:08:02] "GET /static/css/bootstrap-datetimepicker.min.css HTTP/1.1" 404 4544
web_1           | [05/Mar/2018 13:08:02] "GET /static/css/bootstrap-switch.min.css HTTP/1.1" 404 4536
```

I checked in the container whether the static files are being linked to via the ~/.cache/promgen/ (as i found in settings.py) and they seem they arent being exposed through there:
```
$ docker exec -it 3c6beb49d869 /bin/bash
bash-4.3# ls /root/.cache/
pip
bash-4.3# ls ~/.cache/
pip
```

My Dockerfile:
```
FROM line/promgen:v0.25

RUN chmod a+w /etc/prometheus
RUN chown -R promgen /etc/prometheus

USER root

COPY docker/wait-for-it.sh /
COPY docker/bootstrap.sh /
```
i had issues with some volumes inside docker to share configuration files, so thats what the RUN and USER are about, then i have some scripts that help me with automatic deployment. The USER root could be the culprit, however it seems unlikely that I would run into permission issues because I am running the container as root.

And finally for completeness, my docker-compose.yml:
```
version: '2'

services:
  config:
    image: ${AWS_DOCKER_REPOSITORY}/${PROMETHEUS_REPOSITORY}:${CONFIG_IMAGE}-$SHA1
    mem_limit: 16000k

  web:
    image: ${AWS_DOCKER_REPOSITORY}/${PROMETHEUS_REPOSITORY}:${PROMGEN_IMAGE}-$SHA1
    entrypoint: "/wait-for-it.sh"
    environment:
      PROMGEN_USER: ${PROMGEN_USER}
      PROMGEN_EMAIL: ${PROMGEN_EMAIL}
      PROMGEN_PASSWORD: ${PROMGEN_PASSWORD}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      PROMGEN_PORT: ${PROMGEN_PORT}
    links:
      - mysql
      - prometheus
      - redis
    command: ["-t", "0", "mysql:3306", "--", "sh", "/bootstrap.sh"]
    ports:
      - "8000:8000"
    mem_reservation: 256M
    volumes_from:
      - config:rw

  worker:
    image: ${AWS_DOCKER_REPOSITORY}/${PROMETHEUS_REPOSITORY}:${PROMGEN_IMAGE}-$SHA1
    environment:
      PROMGEN_USER: ${PROMGEN_USER}
      PROMGEN_EMAIL: ${PROMGEN_EMAIL}
      PROMGEN_PASSWORD: ${PROMGEN_PASSWORD}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    links:
      - mysql
      - prometheus
      - redis
    command: worker -l info --queues localhost,celery
    mem_reservation: 64M
    volumes_from:
      - config:rw

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /opt/data/mysql/:/var/lib/mysql
    mem_reservation: 64M

  redis:
    image: redis
    mem_reservation: 64M
```
